### ISSUE TITLE
Boş mesaj atıyor

### ISSUE THREAD

**Issue by AltAirFr** [XianThi/c2msgbot#1]
Sadece bildirim ekranı çıkıyor mesaj içeriği gitmiyor.

**Comment by XianThi** [comment]
if you try with non anon username and password, its can not work. You must have an anon username. You will own your account's anon username and password with Man-in-the-middle attack.

You can try like that for mitm attack : 

https://gist.github.com/XianThi/3ccc4d2884dbd278f4bc3d5c7131ec64#file-c2unban-md

**Comment by AltAirFr** [comment]
Sen adamın dibisin!
